// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALkk4GwHWPygOFVbVRX4XXTGsRsVkI7w4',
    appId: '1:1018592171441:web:c4a806fec8d045a8291990',
    messagingSenderId: '1018592171441',
    projectId: 'timetracker-2f45c',
    authDomain: 'timetracker-2f45c.firebaseapp.com',
    storageBucket: 'timetracker-2f45c.appspot.com',
    measurementId: 'G-Q53YJ07XS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc1xdG8zfK3rpeAqlPRwdkTJgW6A4MTGE',
    appId: '1:1018592171441:android:8a4c3c6385288db8291990',
    messagingSenderId: '1018592171441',
    projectId: 'timetracker-2f45c',
    storageBucket: 'timetracker-2f45c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1uq_hvwl2dTskvFypKNWi0EZV66fy6qk',
    appId: '1:1018592171441:ios:38973086aa038cda291990',
    messagingSenderId: '1018592171441',
    projectId: 'timetracker-2f45c',
    storageBucket: 'timetracker-2f45c.appspot.com',
    iosClientId: '1018592171441-9govcj37cpkkr8ctmls0jkgdol8k8qt6.apps.googleusercontent.com',
    iosBundleId: 'com.jonathan',
  );
}
